# Taller de introducción a R usando scripts	

Contenido 

     0. Preliminares                                                                       
     1.	R como calculadora                                                                  
     2.	Objetos y funciones                                                                  
     3.	Paquetes y librerías                                                                
     4.	Datos importar/exportar                                                             
     5.	Subscripts                                                                          
     6.	Recodificación de variables                                                         
     7.	Reducir y combinar bases de datos                                                   
     8.	Gráficos                                                                            
     9.	Estadísticas uni/bivariadas

### Preliminares

Los 'scripts' en R equivalen a los 'do' de Stata y a las Syntax de SPSS

El signo de '#' se usa para hacer comentarios en los scripts (lo cual es muy recomendable)

Para ejecutar un comando se ubica al cursor en la línea o se selecciona un conjunto de
líneas y se oprimen las teclas <Ctrl> + <R>


 El R-project se gestiona con recursos provenientes de donaciones, apoyos y subvenciones, por
 lo que se insta a los usuarios a que le den el crédito cuando se haya utilizado el programa

In [1]:
citation()


To cite R in publications use:

  R Core Team (2016). R: A language and environment for statistical
  computing. R Foundation for Statistical Computing, Vienna, Austria.
  URL https://www.R-project.org/.

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {R: A Language and Environment for Statistical Computing},
    author = {{R Core Team}},
    organization = {R Foundation for Statistical Computing},
    address = {Vienna, Austria},
    year = {2016},
    url = {https://www.R-project.org/},
  }

We have invested a lot of time and effort in creating R, please cite it
when using it for data analysis. See also ‘citation("pkgname")’ for
citing R packages.


Notar que en la consola (Console) se despliga el resultado de la ejecución del comando

Los simbolos ' > | ' al final de la consola significan que se ha ejecutado exitosamente el 
comando. 

Un ' + ' al final de la consola es indicativo de que el comando ejecutado está incompleto.
Esto normalmente ocurre cuando no se cierra un parétesis o un corchete.

In [3]:
citation(

ERROR: Error in parse(text = x, srcfile = src): <text>:2:0: unexpected end of input
1: citation(
   ^


In [ ]:
Si se cometí un error, ubicarse en la consola y oprimir <Esc>
  
Para obtener ayuda (Help):
Google
Si se conoce el nombre de la función, anteponer ' ? ' a dicha función

In [4]:
 ?citation

Una ayuda más escueta se obtiene al oprimir <Tab> al final del nombre de la función
Solo funciona en RStudio

También se puede utilizar la función help()

In [8]:
help("citation")

In [6]:
help("!=") # Muestra la ayuda para el caracter !=

Si no se recuerda el nombre de la función, pero se sabe el tema sobre el que se desea 
obtener ayuda, utilizar la función help.search("tema")

In [10]:
help.search("citing R")

Directorio de trabajo  

La función getwd() nos dice dónde está el directorio de trabajo actual

In [11]:
getwd() 

[1] "/Users/amagaldi/Google Drive/Taller_R"

Si deseo cambiar, digamos a la carpeta Intro_R del escritorio, utilizo la función setwd() 
y entre comillas pongo la ruta

In [12]:
setwd("/Users/amagaldi/Google Drive/Taller_R/")

esto es en windows
setwd("?????")

en linux es algo así como:
setwd("/home/amagaldi/Desktop/Intro_R") 

### R como calculadora

In [1]:
2 + 3

[1] 5

In [2]:
5 - 6

[1] -1

In [3]:
2 * 3

[1] 6

In [4]:
3/7

[1] 0.4285714

In [5]:
2^3

[1] 8

In [6]:
2^-3

[1] 0.125

Dos o más expresiones se pueden colocar en una sola línea, siempre y cuando estén separadas
por punto y coma 

In [9]:
2+3; 5*7; 3-7 ; 2/2 ; 2^10

[1] 5

[1] 35

[1] -4

[1] 1

[1] 1024

#### Operadores

In [ ]:
+, -, *, /, ^  son operadores aritméticos
  
>, >=, <, <=, ==, !=, son operadores relacionales
  
!, &, |, lógicos
  
: , crean una secuencia

In [ ]:
1:40

#### Objectos en R

El signo  ' <- ' asigna valores a objetos

Valores numéricos

In [10]:
 x <- 20

In [11]:
 y <- 49

In [12]:
x + 5

[1] 25

In [13]:
x + y

[1] 69

Caracteres

In [21]:
aqui <- "Juriquilla" ; mejor<- " UMDI"

In [22]:
 aqui ;mejor

[1] "Juriquilla"

[1] " UMDI"

In [ ]:
Ejercicio 
¿Cuál es la función para borrar objetos de la memoria de R? 
Usarla para borrar los objetos 'x' y 'y'

 Vectores

Objetos que contienen varios valores
  
Vectores numéricos

In [23]:
altura <- c(167, 172, 153, 164, 182, 167, 171, 155, 163, 170)

In [30]:
altura

[1] 167 172 153 164 182 167 171 155 163 170

In [28]:
altura79 <- altura[7:9]

In [29]:
altura79

[1] 167 172 153

In [31]:
altura + 20

[1] 187 192 173 184 202 187 191 175 183 190

In [33]:
# Dividir cada observación por un número dado (pasar de cm a m)
  
(altura+20)/100

[1] 1.87 1.92 1.73 1.84 2.02 1.87 1.91 1.75 1.83 1.90

In [34]:
# Elevar cada observación a determinada potencia
  
altura^2

[1] 27889 29584 23409 26896 33124 27889 29241 24025 26569 28900

In [35]:
# Almacenar la altura en mts y en cm2 en un nuevo objeto
  
altura_mts <- altura/100

In [36]:
altura_mts

[1] 1.67 1.72 1.53 1.64 1.82 1.67 1.71 1.55 1.63 1.70

In [37]:
altura_cm2 <- altura^2 

In [38]:
altura_cm2

[1] 27889 29584 23409 26896 33124 27889 29241 24025 26569 28900

In [39]:
# Combinar objetos: Índice de masa corporal (IMC)
  
  # El peso de los 10 individuos anteriores
  
peso <- c(86, 74, 83, 50, 78, 66, 66, 51, 50, 55)

In [40]:
peso

[1] 86 74 83 50 78 66 66 51 50 55

In [41]:
 # Objeto con el IMC (peso / altura_mts^2)
  
imc <- peso/altura_mts^2

In [42]:
imc

[1] 30.83653 25.01352 35.45645 18.59012 23.54788 23.66524 22.57105 21.22789
 [9] 18.81892 19.03114

In [43]:
# La función round() permite redondear los valores
  
imc <- round(imc, 2)

In [44]:
imc # Notar que asigna el valor redondeado de imc al objeto imc. 
# Así, el objeto imc tendra 2 decimales (ya no 5 como al principio)

[1] 30.84 25.01 35.46 18.59 23.55 23.67 22.57 21.23 18.82 19.03

Vectores con caracteres

In [45]:
educacion <- c("Primaria", "Secundaria", "Bachillerato", "Licenciatura", "Maestría", "Doctorado")

In [47]:
educacion[5] # Pemiter ver el quito elemento del vector educación

[1] "Primaria"

In [ ]:
# Matrices
  
# Convertir al vector altura en a matriz m_altura de 5 filas y 2 columnas. 
  
altura

In [48]:
m_altura <- matrix(altura,nrow=5,ncol=2, byrow=FALSE)  

In [50]:
m_altura  ; altura

[,1] [,2]
[1,] 167  167 
[2,] 172  171 
[3,] 153  155 
[4,] 164  163 
[5,] 182  170

[1] 167 172 153 164 182 167 171 155 163 170

In [53]:
# Notar que el parámetro 'byrow=FALSE' hace que los elementos del vector peso 
  # sean desplegados verticalmente en la matriz m_altura. Si obtamos por la opción
  # 'TRUE', los elementos del vector serán desplegados horizontalmente.   
  
  m_altura <- matrix(altura,nrow=5,ncol=2, byrow=TRUE) 

In [65]:
m_altura ; altura

[,1] [,2] [,3] [,4] [,5]
[1,] 167  172  153  164  182 
[2,] 167  171  155  163  170

[1] 167 172 153 164 182 167 171 155 163 170

In [ ]:
# Convertir al vector altura en a matriz m_altura de 5 filas y 2 columnas. 
  
peso

In [55]:
m_peso <- matrix(peso,nrow=2,ncol=5, byrow=FALSE) 

In [56]:
m_peso

[,1] [,2] [,3] [,4] [,5]
[1,] 86   83   78   66   50  
[2,] 74   50   66   51   55

In [57]:
 # Para obtener el ij-esimo elemento de una matriz M se escribe M[i,j].
  
m_peso[2,4] # Elemento situado en el 2do renglón, 4ta columna de la matriz m_peso

[1] 51

In [59]:
# Desplegar la i-esima fila de la matriz m_altura
  
m_altura[1,]  # 2da fila de la matriz m_altura

[1] 167 172 153 164 182

In [67]:
m_altura

[,1] [,2] [,3] [,4] [,5]
[1,] 167  172  153  164  182 
[2,] 167  171  155  163  170

In [64]:
# Desplegar la j-esima columna de m_peso
  
m_peso[,1]  # 5ta columna de la matriz m_peso

[1] 86 74

In [68]:
# Desplegar los elementos de la columna j contenidos entre las filas r y s de M  
  
m_altura[2,2:4]  # Elementos de la columna 2 contenidos entre las filas 2 y 4 de la matriz m_altura
  

[1] 171 155 163

Factor

In [69]:
#Objeto que almacena el valor de una variable nominal. Ejemplo: sexo, colores, ...
  
sexo <- factor(c("Hombre", "Hombre", "Mujer", "Mujer", "Hombre")) 

In [70]:
summary(sexo)  

Hombre  Mujer 
     3      2

data.frame
  
Es más general que una matriz. Las columnas pueden tener diferentes clases de objetos
(numéricos, caracteres, factores, etc)

In [71]:
datos <- data.frame(c(0,1),c("Rojo", "Amarillo"), c(TRUE,FALSE)) 

In [75]:
datos

X1 X2       X3   
1 0  Rojo      TRUE
2 1  Amarillo FALSE

In [ ]:
View(datos)

In [72]:
names(datos) <- c("X1","X2","X3")

In [ ]:
View(datos)

Atributos de los objetos
  
Todo objeto tiene dos atributos intrínsecos: tipo y longitud.
  
El tipo se refiere a la clase básica de los elementos en el objeto (numérico, caracter, lógico)
La longitud es el número de elementos en el objeto.

In [73]:
 # Tipo  
  mode(peso)       ;
  mode(m_altura)   ; 
  mode(datos)      ; 

[1] "numeric"

[1] "numeric"

[1] "list"

In [74]:
 # Longitud  
  length(peso)      ;
  length(m_altura)  ;
  length(datos)     ;

[1] 10

[1] 10

[1] 3

Ejercicio. 
Crear un data.frame con nuestros datos sobre edad, estatura, sexo, municipio de residencia